### ISSUE TITLE
Unable to get the jibri status

### ISSUE THREAD

**Issue by lunika** [openfun/jitsi-k8s#15]
## Bug Report

**Problematic behavior/code**

When jibri pod is starting, The metadata-updater script raises an unhandle error

```
Traceback (most recent call last): 
File "/usr/local/lib/python3.8/urllib/request.py", line 1354, in do_open
metadata-updater     h.request(req.get_method(), req.selector, req.data, headers,
File "/usr/local/lib/python3.8/http/client.py", line 1256, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1302, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1011, in _send_output
self.send(msg)
File "/usr/local/lib/python3.8/http/client.py", line 951, in send
self.connect()
File "/usr/local/lib/python3.8/http/client.py", line 922, in connect
self.sock = self._create_connection(
File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
raise err
File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:                                                                                                       
Traceback (most recent call last):
File "/opt/jibri-metadata-updater/jibri-metadata-updater.py", line 113, in <module>
new_jibri_status = get_jibri_status()
File "/opt/jibri-metadata-updater/jibri-metadata-updater.py", line 55, in get_jibri_status
response = request.urlopen(jibri_health_api)
File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
return opener.open(url, data, timeout)
File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
response = self._open(req, data)
File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
result = func(*args)
File "/usr/local/lib/python3.8/urllib/request.py", line 1383, in http_open
return self.do_open(http.client.HTTPConnection, req)
File "/usr/local/lib/python3.8/urllib/request.py", line 1357, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused> 
```

**Expected Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. restart a jibri pod

**Comment by lunika** [comment]
This stack trace comes from a `logging.exception` in an exception handler. So the exception is correctly caught.
